collections:
  category:
    output: true
  tag:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
  -
    scope:
      path: ""
      type: tag
    values:
      layout: "tag"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vanessa"
      authorWebsite: "https:vanessaesanto.com"
      gravatar: "https://s.gravatar.com/avatar/4a92996328d78a1115709b690d8df067?s=150"
